# Generated by Django 5.1.3 on 2025-01-22 05:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
