# Generated by Django 5.1.3 on 2025-01-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_blog_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
